USE [master]
GO

/****** Object:  Database [OnlineStore]    Script Date: 29-07-2023 20:25:19 ******/
CREATE DATABASE [OnlineStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnlineStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\OnlineStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OnlineStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\OnlineStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnlineStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OnlineStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OnlineStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OnlineStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OnlineStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OnlineStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [OnlineStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OnlineStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OnlineStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OnlineStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OnlineStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OnlineStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OnlineStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OnlineStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OnlineStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OnlineStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OnlineStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OnlineStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OnlineStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OnlineStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OnlineStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OnlineStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OnlineStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OnlineStore] SET RECOVERY FULL 
GO

ALTER DATABASE [OnlineStore] SET  MULTI_USER 
GO

ALTER DATABASE [OnlineStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OnlineStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OnlineStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OnlineStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OnlineStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OnlineStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [OnlineStore] SET QUERY_STORE = ON
GO

ALTER DATABASE [OnlineStore] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [OnlineStore] SET  READ_WRITE 
GO

